version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      DB_HOST: mongodb://database:27017/falemais
      PORT: 3333
    ports:
      - "3333:3333"
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:9.6
    container_name: database
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
